### ISSUE TITLE
Date in revision field when no revisions on sheet

### ISSUE THREAD

**Issue by shtirlitsDva** [acnicholas/scaddins#3]
Hi
So, I've discovered that the add-in reads some kind of revision date into the revision field when there's no revisions on sheet.
When there's a revision it functions as intended.
See screenshot, I've marked with red:
1. First sheet no revision -- wrong data in field
2. Second sheet revision A -- correct data in field
![2017-11-10 16_54_38-scexport - scott carver export utility - by andrew nicholas](https://user-images.githubusercontent.com/12258139/32666639-64fc866c-c638-11e7-9402-2461fb5fab33.png)

**Comment by acnicholas** [comment]
Hi @shtirlitsDva ,

I agree,  this is not ideal.
I've added an option disable/enable this behavior (see commit https://github.com/acnicholas/scaddins/commit/be223472f05d9803915c3a65ea050611f4a95f07)

You can access the setting in the options dialog:

![emptyrevisiondate](https://user-images.githubusercontent.com/3241225/32760948-cf55df90-c944-11e7-8cc6-f4edb7a0dd02.PNG)
