### ISSUE TITLE
No information about Print Setting

### ISSUE THREAD

**Issue by shtirlitsDva** [acnicholas/scaddins#4]
Hi
I cannot find any information where to set the Print Setting for each sheet.

Is it in a custom parameter?

Best regards
Michail

**Comment by shtirlitsDva** [comment]
It seems the program reads this information from the sheet size.

**Comment by acnicholas** [comment]
@shtirlitsDva ,

This is correct, page sizes are determined from the sheet size.

At the moment only A-series paper sizes are supported. see issue #1

**Comment by acnicholas** [comment]
Closing as Revit's new inbuilt PDF exporter can automatically determine page size.
The new export method will be supported with the initial 2022 build.
